### ISSUE TITLE
Need For Speed™ Most Wanted [PCSE00089]

### ISSUE THREAD

**Issue by Zangetsu38** [Vita3K/compatibility#209]
# Game summary
- Game name: Need For Speed™ Most Wanted
- Game serial: PCSE00089
- Game version: 1.00

# Vita3K summary
- Version: v0.1
- Build number: 1071
- Commit hash: https://github.com/vita3k/vita3k/commit/205c3ac

# Test environment summary
- Tested by: Zangetsu38
- OS: Windows 10
- CPU: AMD Ryzen 2700X
- GPU: NVIDIA GTX 1080 Ti
- RAM: 16 GB DDR4 3600 mhz

# Issues
- stop boot on unicorn error after have generate lot shader

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/3266650/vita3k.log)

**Comment by benderscruffy** [comment]
Vita3K v0.1.5 2603-8daf6c6f
comes up with the placeholder
then a black screen and the emulator crashes out
[vita3k.log](https://github.com/Vita3K/compatibility/files/8811333/vita3k.log)

**Comment by UnearthlyGoose** [comment]
Now ingame with major bugs. Also doesnt work with vulkan.
![unknown](https://user-images.githubusercontent.com/96787750/197181733-56c87be6-0d3e-4e5f-a84b-482f36edf210.png)

**Comment by bizz91** [comment]
Any status as of now?

**Comment by JRHJ510** [comment]
Game loads, graphics are jacked up completely, everything is green and blue, no sound.
Tab S7, 8GB RAM, Turnip v22

**Comment by TheComputerGuy96** [comment]
Interesting progress with commit https://github.com/Vita3K/Vita3K/commit/39f794515a3855a8fdf7556dc4f1ca027b94fd81 (with RADV (Mesa 22.3.5) on my AMD Renoir iGPU):
![Screenshot of NFS Most Wanted with green/blue artifacts everywhere](https://user-images.githubusercontent.com/19169000/220790994-d6398b55-5bc9-47ca-9967-294e2ca5b83d.png)

On my NVIDIA dGPU (GTX 1650 Ti with 525.89.02 driver) the game world (the non-HUD parts) are completely black for some reason

The audio still doesn't work (maybe some stubs are the issue?)

The game freezes/crashes after switching to the Porsche car at the start of the game though (maybe the auto-saving is broken or the NGS implementation?)

I did get this backtrace once when using `gdb` though:
<details>
  <summary>gdb backtrace of the car switch crash</summary>
  
  ```
  #0  0x00007f125c4a08ec in ?? () from /usr/lib/libc.so.6
#1  0x00007f125c451ea8 in raise () from /usr/lib/libc.so.6
#2  0x00007f125c43b53d in abort () from /usr/lib/libc.so.6
#3  0x00007f125c6d30e2 in std::__glibcxx_assert_fail (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:60
#4  0x000055828b1f885e in std::unique_ptr<std::mutex, std::default_delete<std::mutex> >::operator* (this=0xa8) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/unique_ptr.h:445
#5  ngs::deliver_data (mem=..., source=<optimized out>, output_port=<optimized out>, data_to_deliver=...) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/ngs/src/route.cpp:38
#6  0x000055828b1f78e1 in ngs::VoiceScheduler::update (this=0x40da15a38, kern=..., mem=..., thread_id=303) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/ngs/src/scheduler.cpp:176
#7  0x000055828af7d6d1 in export_sceNgsSystemUpdate (emuenv=..., thread_id=303, export_name=<optimized out>, handle=...) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/modules/SceNgsUser/SceNgs.cpp:369
#8  0x000055828afa0608 in call<unsigned int, Ptr<ngs::System>, 0ul> (export_fn=0x55828af7d220 <export_sceNgsSystemUpdate(EmuEnvState&, int, char const*, Ptr<ngs::System>)>, export_name=0x55828a25f606 "sceNgsSystemUpdate", 
    args_layout=..., state=..., thread_id=303, cpu=..., emuenv=...) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/module/include/module/bridge.h:39
#9  bridge<unsigned int, Ptr<ngs::System> >(unsigned int (*)(EmuEnvState&, int, char const*, Ptr<ngs::System>), char const*)::{lambda(EmuEnvState&, CPUState&, int)#1}::operator()(EmuEnvState&, CPUState&, int) const (
    this=0x7f11206247b0, emuenv=..., cpu=..., thread_id=303) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/module/include/module/bridge.h:61
#10 0x000055828a978f8b in std::function<void (EmuEnvState&, CPUState&, int)>::operator()(EmuEnvState&, CPUState&, int) const (this=0x7f11bbff9f90, __args=303, __args=303, __args=303)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:591
#11 call_import (emuenv=..., cpu=..., nid=1750009868, thread_id=0) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/modules/module_parent.cpp:118
#12 0x000055828b21045a in std::function<void (CPUState&, unsigned int, int)>::operator()(CPUState&, unsigned int, int) const (this=0x15293, __args=303, __args=303, __args=303)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:591
#13 CPUProtocol::call_svc (this=0x55828de4ec80, cpu=..., svc=<optimized out>, pc=<optimized out>, thread=...) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/kernel/src/cpu_protocol.cpp:55
#14 0x000055828b206935 in ThreadState::run_loop (this=0x7f11350d6430) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/kernel/src/thread.cpp:206
#15 0x000055828b2048d5 in thread_function (data=<optimized out>) at /mnt/storagebeast/build-dirs/AUR/vita3k-git/src/vita3k/vita3k/kernel/src/kernel.cpp:75
#16 0x00007f125cb69dbb in ?? () from /usr/lib/libSDL2-2.0.so.0
#17 0x00007f125c49ebb5 in ?? () from /usr/lib/libc.so.6
#18 0x00007f125c520d90 in ?? () from /usr/lib/libc.so.6
  ```
  
</details>

**Comment by ajmalshaikh88** [comment]
Hi Team Any Update on This Game 

About Graphic Fixing as i am also unable to play Blue screen come 
Device : Poco X3 pro
Processor : Snapdragon 860
Chipset | Qualcomm Snapdragon 860 (7 nm)
CPU : Octa-core (1x2.96 GHz Kryo 485 Gold & 3x2.42 GHz Kryo 485 Gold & 4x1.78 GHz Kryo 485 Silver)
GPU : Adreno 640

**Comment by bagarang** [comment]
# Vita3K summary
- Version: v0.1.8
- Build number: 3305
- Commit hash: https://github.com/vita3k/vita3k/commit/eb28b844
- CPU backend: Dynarmic
- GPU backend: Vulkan

**Comment by benjamintoledo** [comment]
# Vita3K summary
- Version: v0.2.0
- Build number: 3565
- Commit hash: https://github.com/vita3k/vita3k/commit/17886d82
- CPU backend: Dynarmic
- GPU backend: Vulkan
# Environment summary
- Tested by: benjamintoledo
- OS: Windows 11
- CPU: AMD Ryzen 5 4600G
- GPU: AMD Radeon(TM) 8GB
# Issues
- Framerate drops (maximum to 12 FPS)
- Small graphical errors
- Intensive lightning
# Video
https://www.youtube.com/watch?v=yFRSBsYeZQU
# Recommended label
- Ingame+

**Comment by Perfectxboxer** [comment]
Audio is still missing, sometimes by a short time the audio works but not fully and it's less a second, it have occasionally graphical glitches , but now it is a bit more playable , not fully cause at some point the game will crash , can't take a screenshot cause the emulator doesn't let me do it , there is no green screen glitches so I think this is getting better

**Comment by LeeRAY61** [comment]
**Vita3K Summary**

Version: v0.2.0
Build number: 3691
Commit hash: https://github.com/Vita3K/Vita3K/commit/17886d82
CPU backend: Dynarmic
GPU backend: Vulkan

**Environment Summary**

Tested by: ChuckY
OS: Microsoft Windows 11 (build 22631)
CPU: 13th Gen Intel(R) Core(TM) i5-13500H | 16 Threads | 3.187 GHz
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
RAM: 16 GB

**Issues**

There are some minor graphical glitches but it is playable. You can find the best graphical settings by trial and error method. The best graphical settings I used are shown in the screenshot below.

![Ekran görüntüsü 2024-11-27 151715](https://github.com/user-attachments/assets/fb67860d-d619-4bbb-bbb6-25e1b1e61b7f)

**Screenshots**

![Ekran görüntüsü 2024-11-27 151629](https://github.com/user-attachments/assets/71807dc3-207f-44eb-a229-cb5a7ef65554)
![Ekran görüntüsü 2024-11-27 151525](https://github.com/user-attachments/assets/eb013f12-6911-427d-bf95-da3ce67456c5)
![Ekran görüntüsü 2024-11-27 151458](https://github.com/user-attachments/assets/83878ff7-52de-4bf2-9e2d-e9630d81c66c)


**Recommended label**
Playable

**Comment by Danexca** [comment]
81895319

**Comment by benjamintoledo** [comment]
# App summary
- App name: Need For Speed™ Most Wanted
- App serial: PCSE00089
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3691
- Commit hash: https://github.com/vita3k/vita3k/commit/31826697
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: Benjamintoledo
- OS: Windows 11
- CPU: AMD Ryzen 5 4600G
- GPU: AMD Radeon(TM) Graphics (Vega 7)

# Issues
- No audio
- Small graphic erros

# Screenshot
<img width="722" alt="Nid for espid" src="https://github.com/user-attachments/assets/45863835-44e5-4945-9942-e81a62be6441">

# Log
[vita3k.log](https://github.com/user-attachments/files/17966011/vita3k.log)

# Recommended labels
- Ingame+
- Audio missing

**Comment by ghost** [comment]
Same in android
Snapdragon 7s Gen 2

**Comment by RetroGameTalk** [comment]
> **Vita3K Summary**
> 
> Version: v0.2.0 Build number: 3691 Commit hash: [Vita3K/Vita3K@17886d82](https://github.com/Vita3K/Vita3K/commit/17886d82) CPU backend: Dynarmic GPU backend: Vulkan
> 
> **Environment Summary**
> 
> Tested by: ChuckY OS: Microsoft Windows 11 (build 22631) CPU: 13th Gen Intel(R) Core(TM) i5-13500H | 16 Threads | 3.187 GHz GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU RAM: 16 GB
> 
> **Issues**
> 
> * The biggest problem is still no sound.
> * There are some minor graphical glitches but it is playable. You can find the best graphical settings by trial and error method.
> * The best graphical settings I used are shown in the screenshot below.
> 
> ![Ekran görüntüsü 2024-11-27 151715](https://private-user-images.githubusercontent.com/98396822/390406918-fb67860d-d619-4bbb-bbb6-25e1b1e61b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0Njk1NzcsIm5iZiI6MTczNjQ2OTI3NywicGF0aCI6Ii85ODM5NjgyMi8zOTA0MDY5MTgtZmI2Nzg2MGQtZDYxOS00YmJiLWJiYjYtMjVlMWIxZTYxYjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDAwMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZmYwYjhjZjMzYWEwNjUyMTA3OTU0YThkYzEzMDhhODYyYzJiM2ViMDczZDAyYWRlNmQ5OGE3NjMyODAzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3WJPUl2f_9J482Boh41NZd4a4N3eJby2xIE4GhASO48)
> 
> **Screenshots**
> 
> ![Ekran görüntüsü 2024-11-27 151629](https://private-user-images.githubusercontent.com/98396822/390407253-71807dc3-207f-44eb-a229-cb5a7ef65554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0Njk1NzcsIm5iZiI6MTczNjQ2OTI3NywicGF0aCI6Ii85ODM5NjgyMi8zOTA0MDcyNTMtNzE4MDdkYzMtMjA3Zi00NGViLWEyMjktY2I1YTdlZjY1NTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDAwMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Njc5ZDExMmVmZTU4ZWJmMzQ2YjkzZGZmNDliYjY5MmY0ZWZlMzY2YjJhZWZmYzM1YjhmYmIxN2E2ZjcyYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ah6GSV3YkI9onUgBdcanQAi1HAQ5YO_k3_1WOHpxEI) ![Ekran görüntüsü 2024-11-27 151525](https://private-user-images.githubusercontent.com/98396822/390407324-eb013f12-6911-427d-bf95-da3ce67456c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0Njk1NzcsIm5iZiI6MTczNjQ2OTI3NywicGF0aCI6Ii85ODM5NjgyMi8zOTA0MDczMjQtZWIwMTNmMTItNjkxMS00MjdkLWJmOTUtZGEzY2U2NzQ1NmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDAwMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NTQxOWMyMzk4MDY4ZjIyOGFhYTk4MjBlZTMwNzE1YmQyOGE0YjgxZjc1NTQ4ZDczNTUyYmZlOWExM2FkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6B1Z7cxfIRFzuUDbJbWnKH-e6ywfvETFa7NKdmLEX_E) ![Ekran görüntüsü 2024-11-27 151458](https://private-user-images.githubusercontent.com/98396822/390407370-83878ff7-52de-4bf2-9e2d-e9630d81c66c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0Njk1NzcsIm5iZiI6MTczNjQ2OTI3NywicGF0aCI6Ii85ODM5NjgyMi8zOTA0MDczNzAtODM4NzhmZjctNTJkZS00YmYyLTllMmQtZTk2MzBkODFjNjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDAwMzQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MGE3M2JmZDdhNzQ3MjllMGI4MjhkMTk4MmRlMTAzNjNlMjEzOTJlNWVjODA3MzlkYWQyZTZmMDQyMWYwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9JiqVqEhkry6hOdkHpyVmPjnby8fuyhnr2O_PaCvjrU)
> 
> **Recommended label**
> 
> * Ingame+
> * Graphics bug
> * Audio Missing

I copied your settings and my graphics look nothing like yours, what happened?
![Need For Speed™ Most Wanted_2025-01-10-014351](https://github.com/user-attachments/assets/c16399db-2cdf-4ab4-8b41-30a9c92e64b3)
![Need For Speed™ Most Wanted_2025-01-10-014407](https://github.com/user-attachments/assets/3793d50c-ac19-4c0f-bd7b-2a17a880c561)
![Untitled](https://github.com/user-attachments/assets/fdb52170-624f-437a-a530-4afab0714469)

**Comment by LeeRAY61** [comment]
I haven't any idea, sorry about that buddy. You can find the best graphical settings by trial and error method.

**Comment by starzokc** [comment]
What do yall think that the issue w/the audio comes from?

**Comment by LeeRAY61** [comment]
This may be a problem due to the lack of audio codecs

**Comment by Gst0n** [comment]
Has anyone fixed the shader bug yet? Unfortunately I don't know how to program So all I can do is wait.

**Comment by RexhibHUB** [comment]
The game can be completed 
Previously, Most Wanted 8,7,6,3,2 and 1 tests would crash at a certain point, but the game can now be completed
Also for adds the Audi A1 clubsport quattro
It is the only car that renders its model well 
Tested On a PC with a Ryzen 5 4600h 



![Image](https://github.com/user-attachments/assets/78a7cfc2-8c13-4f05-b259-9b5e56da1a9b)
![Image](https://github.com/user-attachments/assets/6bddae32-c2f7-4ff5-b621-421dde2f1849)

![Image](https://github.com/user-attachments/assets/d6261df8-7ef6-4c46-b9cb-e49d17dd1285)

**Comment by HelderRocket** [comment]
In my case, on a PC (Win 10, RTX 4070, R5 5600, 96 gigabytes of RAM), I managed to run it.
That in itself is already much more than I achieved on my phone. With the Redmagic 9 s pro, the game simply won't load and causes the emulator to crash.
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0700edec-5f55-433f-ad38-58f0ec82056b" />

**Comment by github-user1112** [comment]
Still issue and no sound

# Vita3K summary
Version: v0.2.1
Build number: 3965
Commit hash: https://github.com/Vita3K/commit/9916d86
GPU backend: Vulkan

# Test environment summary
Tested by: gtihub-user
OS: Linux Mint 22.3
CPU: AMD Ryzen 5 5600
GPU: Radeon Rx 6600
RAM: 16 GB

<img width="960" height="1042" alt="Image" src="https://github.com/user-attachments/assets/2948aa90-6752-4acc-90e3-81d23f25a4ab" />

**Comment by StrykeCalamity** [comment]
# App summary
- App name: Need For Speed™ Most Wanted
- App serial: PCSE00089
- App version: 1.01 

# Vita3K summary
- Version: v0.2.1 
- Build number: 4037
- Commit hash: https://github.com/vita3k/vita3k/commit/f531d803 
- GPU backend: Vulkan

# Test environment summary
- Tested by: StrykeCalamity
- OS: Windows 10
- CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz | 4 Threads | 2.712 GHz
- GPU: Intel(R) HD Graphics 620
- RAM: 8 GB

# Issues
There No Audio other then very silent static, irrespective of changes to Audio Settings
And for Graphic bloom issue Turn off "Disable Surface Sync" & also random background rendering in black for 1 sec and then fixing itself, and also the logo of current car appears as messed up render at multiple place.
There are no other major issue

# Screenshots

<img width="960" height="544" alt="Image" src="https://github.com/user-attachments/assets/b5143cb3-ed6a-471f-b321-99321bd70682" />

<img width="960" height="544" alt="Image" src="https://github.com/user-attachments/assets/166fe2eb-60f1-433c-b657-81ca5fd6bea5" />
Bloom is no longer an Issue if you Turn off "Disable Surface sync" in custom Config

<img width="960" height="544" alt="Image" src="https://github.com/user-attachments/assets/192c931c-92d3-414f-b0a2-c05ac11e54f6" />

<img width="960" height="544" alt="Image" src="https://github.com/user-attachments/assets/26b9330d-6e58-40b8-a9f2-cf3781f83c84" />

<img width="960" height="544" alt="Image" src="https://github.com/user-attachments/assets/b14dc714-9e01-482f-be95-9e20f3dbed87" />

<img width="960" height="544" alt="Image" src="https://github.com/user-attachments/assets/d2e078e1-fa52-4933-b49a-a02eb7fc79f4" />

Logo of current car being rendered at weird places
![](https://?)

# Log

[vita3k.log](https://github.com/user-attachments/files/28429286/vita3k.log)


# Recommended labels



- A- Ingame +
- B- Audio Missing
- C- Graphic Bug
- Remove- Anisotropic Bug
